Vagrant.configure("2") do |config|
  config.vm.box = "dev-build-qt"
  config.vm.synced_folder ".", "/vagrant", type: "smb", mount_options: ["domain=yourdomain.com"]
  config.vm.provider "hyperv" do |h|
    h.cpus = 2
    h.memory = "8192"
    h.maxmemory = "8192"
  end
end
